color: true
diff: true
no-warnings: true
node-option:
  - experimental-specifier-resolution=node
  - no-warnings
  - loader=ts-node/esm
package: ./package.json
reporter: dot
spec:
  - test/*.ts
timeout: 90000
throw-deprecation: true
ui: bdd
